title: Stack Problems
description: My Personal Stack Problems
author: Michael Iuzzolino
github: https://github.com/michael-iuzzolino
about: I'm machine learning researcher with the Applied Sciences Group at Microsoft. I'm also a
PhD student in Computer Science at Colorado University Boulder; my advisor is Michael C. Mozer.
disqus_shortname:
google_analytics:

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/michael-iuzzolino"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: CV
      url: /cv/

url: "https://michael-iuzzolino.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
